### ISSUE TITLE
Wemo beta results

### ISSUE THREAD

**Issue by timmeade** [rudders/homebridge-wemo#27]
Well it worked great for about 30 minutes.

I did see some odd results in Home+ app.  Said:   Error. Communication to dehumidifier failed Value is lower than minium.

But;  it still turned on/off even with error.  Home app and Eve both worked fine no error.

Now 30 mins later;

Not working;

Logs 
```
[8/5/2021, 9:53:19 AM] [Wemo] [Dehumidifier] requestDeviceUpdate() error:  at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-wemo/node_modules/p-queue/dist/index.js:8:22).
[8/5/2021, 9:53:28 AM] [Wemo] [Dehumidifier] could not update from internal change as  at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-wemo/node_modules/p-queue/dist/index.js:8:22).
```

And i just tried it again in home app and it works again.

```
[8/5/2021, 9:57:10 AM] [Wemo] [Dehumidifier] current state [purifying].
```

**Comment by bwp91** [comment]
I've just released a new beta, with a few more changes, one being improving the log language to make it clearer what is going on.

In your log snippet above, the `at Object.<anonymous>` actually meant a timeout on the connection, meaning that the device was disconnected from wifi at the time of command being sent

**Comment by bwp91** [comment]
I've also added a global 'disable upnp' option so that might make it simpler to try this out

**Comment by bwp91** [comment]
Will mark this as complete as the beta has been released now. Obviously if you/anyone encounters any issues then get in contact.

Thanks for trying the beta!
