### ISSUE TITLE
exception while setting power state

### ISSUE THREAD

**Issue by dwery** [rudders/homebridge-wemo#3]
```
[Coperta] Setting power state on the 'Coperta' to 1
[Coperta] Error setting power state to 1 on the 'Coperta'
[Coperta] WARNING: setBinaryState called its callback more than once! Discarding the second one.
[Coperta] Error setting power state to 1 on the 'Coperta'
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someo
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at WeMoAccessory.<anonymous> (/usr/lib/node_modules/homebridge-legacy-plugins/accessories/WeMo.js:107:7)
    at /usr/lib/node_modules/homebridge-legacy-plugins/node_modules/wemo/wemo.js:127:5
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-legacy-plugins/node_modules/wemo/wemo.js:99:4)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketCloseListener (_http_client.js:247:9)
    at Socket.emit (events.js:129:20)
    at TCP.close (net.js:485:12)
```

**Comment by rudders** [comment]
I'd suggest moving to Homebridge-platform-wemo - much better support for WEMO.

**Comment by rudders** [comment]
Did this resolve your issue?

**Comment by dwery** [comment]
I'm trying the platform plugin and HomeBridge 0.2.5 but it only finds one of my WeMo devices :-/ even if I tried multiple times. The discovered device does not even show up in the HK configuration, but I guess that's a problem in HomeBridge.

**Comment by rudders** [comment]
Discovery of the wemo devices is very hit or miss unfortunately. Make sure you can see them from the wemo app first. Then start homebridge. Multiple wifi routers or network connections are often a problem also. Anything unusual about your network?

**Comment by rudders** [comment]
Did you get the platform to work eventually?
