### ISSUE TITLE
Crockpot - receiving update failed

### ISSUE THREAD

**Issue by danielsza** [rudders/homebridge-wemo#61]
[02/06/2022, 21:17:14] [Homebridge UI] Homebridge log truncated by admin.
[02/06/2022, 21:17:23] [Wemo] [Slow Cooker] receiving update failed as Invalid value passed at default.externalModeUpdate (file:///usr/local/lib/node_modules/homebridge-wemo/lib/device/crockpot.js:350:17).

**Comment by bwp91** [comment]
Hi @danielsza 

Can you update to the beta of the plugin and try to regenerate this error message? It should contain more info about the data the plugin received from the device.

Thanks!

**Comment by danielsza** [comment]
No problem.

I updated the the latest beta, also I noticed my node.js was not one of the supported versions, so that’s been updated too.

Here is the current error

[06/06/2022, 08:25:24] [Homebridge UI] Homebridge log truncated by admin.
[06/06/2022, 08:25:40] [Wemo] [Slow Cooker] receiving update failed as Unknown value passed [0 number] at default.externalModeUpdate (file:///usr/local/lib/node_modules/homebridge-wemo/lib/device/crockpot.js:350:17).
[06/06/2022, 08:26:10] [Wemo] [Slow Cooker] receiving update failed as Unknown value passed [0 number] at default.externalModeUpdate (file:///usr/local/lib/node_modules/homebridge-wemo/lib/device/crockpot.js:350:17).
